#!/usr/bin/env ruby
#
# mongrel       Startup script for Mongrel by Tim Morgan
#
# chkconfig: - 85 15
# description: mongrel manages Mongrel
#

RAILS_ROOT = "This will be replaced by rake"
PORT = 80

if ['stop', 'restart'].include? ARGV.first
  puts "Stopping #{RAILS_ROOT}..."
  `mongrel_rails stop -c #{RAILS_ROOT} -P log/mongrel.pid`
end

if ['start', 'restart'].include? ARGV.first
  puts "Starting #{RAILS_ROOT} on port #{PORT}..."
  `mongrel_rails start -d -p #{PORT} -e production -c #{RAILS_ROOT} -P log/mongrel.pid`
end

unless ['start', 'stop', 'restart'].include? ARGV.first
    puts "Usage: mongrel {start|stop|restart}"
    exit
end


